# Generated by Django 5.1.6 on 2025-03-03 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sort', 'name'), 'verbose_name': 'Категорія страв', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('sort', 'name'), 'verbose_name': 'Страва', 'verbose_name_plural': 'Страви'},
        ),
    ]
