# Generated by Django 5.1.6 on 2025-03-10 18:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_slug_alter_dish_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', ckeditor.fields.RichTextField()),
                ('reservations', ckeditor.fields.RichTextField()),
                ('opening_hours', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
